"""initial schema

Revision ID: fdf76592a76c
Revises: 
Create Date: 2026-06-24 22:20:37.390624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fdf76592a76c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_course_code'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('idx_course_code'), table_name='courses')
    op.drop_column('courses', 'max_seats')
    op.add_column('enrollments', sa.Column('enrollment_date', sa.Date(), nullable=True))
    op.add_column('professors', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('professors', sa.Column('last_name', sa.String(length=50), nullable=False))
    op.alter_column('professors', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('professors', 'prof_name')
    op.drop_column('professors', 'salary')
    op.add_column('students', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('students', sa.Column('enrollment_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'enrollment_year')
    op.drop_column('students', 'date_of_birth')
    op.add_column('professors', sa.Column('salary', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('professors', sa.Column('prof_name', mysql.VARCHAR(length=100), nullable=False))
    op.alter_column('professors', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_column('professors', 'last_name')
    op.drop_column('professors', 'first_name')
    op.drop_column('enrollments', 'enrollment_date')
    op.add_column('courses', sa.Column('max_seats', mysql.INTEGER(), server_default=sa.text("'60'"), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_course_code'), 'courses', ['course_code'], unique=False)
    op.create_table('feedback',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_code', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('semester', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comments', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('tags', mysql.JSON(), nullable=True),
    sa.Column('needs_review', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_course_code'), 'feedback', ['course_code'], unique=False)
    # ### end Alembic commands ###
